domain = "WestAfrica"
subdomain = "Regional"
model_resolution = "1km"
systemModel = "crest"
systemName = systemModel.upper() + " " + domain.upper() + " " + subdomain.upper()
ef5Path = "/vol_efthymios/NFS07/en279/SERVIR/EF5_WA/ef5"
statesPath = "states/"
precipFolder = "precip/"
modelStates = ["crest_SM", "kwr_IR", "kwr_pCQ", "kwr_pOQ"]
templatePath = "templates/"
templates = "ef5_control_template.txt"
DATA_ASSIMILATION = False
assimilationPath = ""
assimilationLogs = []
dataPath = "outputs/"
tmpOutput = dataPath + "tmp_output_" + systemModel + "/"
SEND_ALERTS = False
smtp_server = "smtp.gmail.com"
smtp_port = 587
account_address = "model_alerts@gmail.com"
account_password = "supersecurepassword9000"
alert_sender = "Real Time Model Alert" # can also be the same as account_address
alert_recipients = ["fixer1@company.com", "fixer2@company.com", "panic@company.com",...]
copyToWeb = False
HindCastMode = True
HindCastDate = "2019-06-04 12:00" #"%Y-%m-%d %H:%M"
server = 'https://arthurhouhttps.pps.eosdis.nasa.gov/gpmdata'
subfolder = '/gis/'
file_prefix = '3B-HHR-GIS.MS.MRG.3IMERG.'
file_suffix = '.V07A.tif'
# Email associated to GPM account
email = 'vrobledodelgado@uiowa.edu'